[package]
name = "sepsplit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.8"
num = "0.4"
binrw = "0.15"
uuid = "1.23"
modular-bitfield = "0.13"
prettytable-rs = "0.10"

[dev-dependencies]
assert_cmd = "2.2"
test-case = "3.3"